BEGIN TRANSACTION;
UPDATE articles SET image = '/images/tzellos.jpg' WHERE id = 195;
UPDATE articles SET image = '/images/predicta.png' WHERE id = 271;
UPDATE articles SET image = '/images/tsolakidis.jpg' WHERE id = 442;
UPDATE articles SET image = '/images/JRaptis.jpg' WHERE id = 491;
UPDATE articles SET image = '/images/Giannopoulou2.jpg' WHERE id = 500;
UPDATE articles SET image = '/images/bachas.jpg' WHERE id = 519;
UPDATE articles SET image = '/images/sakellariou.jpg' WHERE id = 527;
UPDATE articles SET image = '/images/vassis.jpg' WHERE id = 528;
UPDATE articles SET image = '/images/korreslogo.gif' WHERE id = 529;
UPDATE articles SET image = '/images/xatziantoniou2.jpg' WHERE id = 553;
UPDATE articles SET image = '/images/kanioura.jpg' WHERE id = 563;
UPDATE articles SET image = '/images/roberts.jpg' WHERE id = 573;
UPDATE articles SET image = '/images/Axarloglou.jpg' WHERE id = 580;
UPDATE articles SET image = '/images/iliopoulos.jpg' WHERE id = 586;
UPDATE articles SET image = '/images/aggelis.jpg' WHERE id = 595;
UPDATE articles SET image = '/images/drew-rockwell.jpg' WHERE id = 607;
UPDATE articles SET image = '/images/ford.jpg' WHERE id = 612;
UPDATE articles SET image = '/images/hanegby.jpg' WHERE id = 644;
UPDATE articles SET image = '/images/sakellariou.jpg' WHERE id = 667;
UPDATE articles SET image = '/images/PNG_QWeb_People_analytics_ex1.ashx' WHERE id = 1183;
UPDATE articles SET image = '/images/x47dy6VqBAt3WAEcLj1NVcCyxCsbi0y1x5IP9xRE1hc.JPG' WHERE id = 1195;
COMMIT;